### ISSUE TITLE
在部分机器上导出png时会出现无法粘贴的现象

### ISSUE THREAD

**Issue by wutiande** [hufang360/FlashTool#1]
1.最开始是通过CSDN上你的一篇文章认识到JSFL的，感谢分享。[链接](https://blog.csdn.net/hufang360/article/details/81396511)
2.你的这个版本是将选中的所有图片导出为一张大图，然后呢我根据你的思路修改了一下，改成将多选选中的图分别导出为png，是业务需求
3.之前一直用的好的，今天我又使用自己写的版本后发现了如下问题：
- convertToSymbol这一步报错
- ☆通过注释和修改代码，发现在源flash中复制没有问题，但是到新建的doc中粘贴时，没有粘贴到内容☆
- 这个插件有段时间没有修改了，flash版本也没有变，上个月能够正常导出的flash也不行了~
- 我使用了你在这里分享的FLASH工具箱，发现一样的报错，如下图
![image](https://user-images.githubusercontent.com/23185102/90104462-e8cf4a80-dd76-11ea-8455-389788023222.png)
![image](https://user-images.githubusercontent.com/23185102/90104513-fe447480-dd76-11ea-9df5-c4302466b403.png)
我现在无法确定问题所在，希望你能够帮忙看一下，感谢~
- 我的FLASH版本 CS6 V12.0.0.481，同事的flash版本也是一样的
- 我初步怀疑是本地环境或变量有问题，导致复制粘贴失败

**Comment by falali009** [comment]
能否分享下 都出多个图片的的需求~

**Comment by hufang360** [comment]
> 1.最开始是通过CSDN上你的一篇文章认识到JSFL的，感谢分享。[链接](https://blog.csdn.net/hufang360/article/details/81396511)
> 2.你的这个版本是将选中的所有图片导出为一张大图，然后呢我根据你的思路修改了一下，改成将多选选中的图分别导出为png，是业务需求
> 3.之前一直用的好的，今天我又使用自己写的版本后发现了如下问题：
> 
> * convertToSymbol这一步报错
> * ☆通过注释和修改代码，发现在源flash中复制没有问题，但是到新建的doc中粘贴时，没有粘贴到内容☆
> * 这个插件有段时间没有修改了，flash版本也没有变，上个月能够正常导出的flash也不行了~
> * 我使用了你在这里分享的FLASH工具箱，发现一样的报错，如下图
>   ![image](https://user-images.githubusercontent.com/23185102/90104462-e8cf4a80-dd76-11ea-8455-389788023222.png)
>   ![image](https://user-images.githubusercontent.com/23185102/90104513-fe447480-dd76-11ea-9df5-c4302466b403.png)
>   我现在无法确定问题所在，希望你能够帮忙看一下，感谢~
> * 我的FLASH版本 CS6 V12.0.0.481，同事的flash版本也是一样的
> * 我初步怀疑是本地环境或变量有问题，导致复制粘贴失败

很抱歉才看到你的问题，脚本去年12月有更新过，刚在我电脑上测试了下，没有发现问题。
如果问题还在，欢迎你 写邮件给我，hufang360@sina.com。

**Comment by hufang360** [comment]
> 能否分享下 都出多个图片的的需求~

1.0.2更新了，支持逐个导出选中
